---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: spoiled-pdnlabs-com
  namespace: spoiled
spec:
  secretName: spoiled-pdnlabs-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "spoiled.pdnlabs.com"
  dnsNames:
  - "spoiled.pdnlabs.com"
  - "www.spoiled.pdnlabs.com"
  acme:
    config:
    - dns01:
        provider: phoenix-dns
      domains:
      - "spoiled.pdnlabs.com"
      - "www.spoiled.pdnlabs.com"