---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoiled
  labels:
    app: spoiled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoiled
  template:
    metadata:
      labels:
        app: spoiled
    spec:
      containers:
      - name: spoiled
        image: phoenix.azurecr.io/spoiled:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
          - name: SQLALCHEMY_DATABASE_URI
            value: "postgresql://postgres:s${POSTGRES_PASSWORD}@postgres:5432/spoiled"
          - name: APP_ENVIRONMENT
            value: "production"
          - name: APP_HOSTNAME
            value: spoiled
          - name: APP_SECRET_KEY
            value: "${APP_SECRET}"
          - name: REDIS_HOST
            value: "redis-cache"
          - name: REDIS_PASSWORD
            value: ${REDIS_PASSWORD}
          - name: REDIS_PORT
            value: "6381"
          - name: FLASK_APP
            value: "app.py"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: spoiled-autoscaler
  labels:
    app: spoiled
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spoiled
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80 # 40% of 3 requested cpu = 1.2 cores