---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoiled-rq-worker
  labels:
    app: spoiled-rq-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoiled-rq-worker
  template:
    metadata:
      labels:
        app: spoiled-rq-worker
    spec:
      containers:
      - name: spoiled-rq-worker
        image: phoenix.azurecr.io/spoiled:latest
        imagePullPolicy: Always
        command: ["./mpesa_worker_start.sh"]
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
        env:
          - name: SQLALCHEMY_DATABASE_URI
            value: "postgresql://postgres:sWH2UnhsnCUa3rE8@postgres:5432/spoiled"
          - name: APP_ENVIRONMENT
            value: "production"
          - name: APP_HOSTNAME
            value: spoiled
          - name: APP_SECRET_KEY
            value: "s8kc5RQuc0kcHq47LdAwukdHhHA0chj6"
          - name: REDIS_HOST
            value: "redis-cache"
          - name: REDIS_PASSWORD
            value: 33gKn2eZOYISeXvPVmWwxg+5LJg04kBASJLiB5AcZkNZOFqNmv0u7UcduDo1Lia9OsKEJqRKBu2rXV29
          - name: REDIS_PORT
            value: "6381"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: spoiled-rq-worker-autoscaler
  labels:
    app: spoiled-rq-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spoiled-rq-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50