---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pdnlabs-com
  namespace: traefik
spec:
  secretName: pdnlabs-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.pdnlabs.com"
  dnsNames:
  - "*.pdnlabs.com"
  - "pdnlabs.com"
  acme:
    config:
    - dns01:
        provider: phoenix-dns
      domains:
      - "*.pdnlabs.com"
      - "pdnlabs.com"