---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
       # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
    email: dan.nyongesa@outlook.com
       # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
       # Enable the HTTP-01 challenge provider
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
       # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
    email: dan.nyongesa@outlook.com
       # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
       # Enable the HTTP-01 challenge provider
    http01: {}
    solvers:
    - dns01:
         azuredns:
            clientID: "0d114d25-fdf3-409c-99f4-4a557d8df267"
            clientSecretRef:
               name: azuredns-config
               key: CLIENT_SECRET
            subscriptionID: "99527e00-ede6-4833-a379-f75ca7b77a70"
            tenantID: "0794201fa-773d-487f-8c6f-44b2df286e78"
            resourceGroupName: "phoenix"
            hostedZoneName: pdnlabs.com
