apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: traefik-ui-pdnlabs-com
  namespace: traefik
spec:
  secretName: traefik-ui-pdnlabs-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: traefik-ui.pdnlabs.com
  dnsNames:
  - traefik-ui.pdnlabs.com
  acme:
    config:
    - http01:
        ingress: traefik-web-ui
      domains:
      - traefik-ui.pdnlabs.com